// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AIUnittestExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "AIUnittestExtension.056fac22-619c-4134-812a-cd7deb4559f9";
        public const string Name = "AIUnittestExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Long Tran";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
